"$schema" = 'https://starship.rs/config-schema.json'

# inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[java]
disabled = true

[python]
disabled = true

[lua]
disabled = true

[c]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

# [username]
# show_always = true
# style_user = "bg:surface0 fg:text"
# style_root = "bg:surface0 fg:text"
# format = '[ $user ]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:purple)]($style)'
