#!/bin/sh

# Start keybinds
sxhkd &

# Play intro video on login
#mpv --no-border --geometry=100%x100% --fullscreen --no-osd-bar --quiet --mute=yes --vo=gpu --hwdec=auto ~/Videos/intro.mp4 &

# Set your wallpaper
feh --bg-scale ~/Pictures/cyper.jpg &

# Clipboard manager
wl-paste --watch cliphist store &

#copyq to have clipboard
copyq &

# Notification daemon
dunst &

# Preload Alacritty to speed up future launches
#kitty --title preload -e sleep 1000 &

# Start compositor
picom &

# Cursor fix (optional)
xsetroot -cursor_name left_ptr

# Custom scripts
~/.local/bin/battery-notify.sh &
~/.config/i3/touchpad.sh &
~/.config/polybar/launch.sh --colorblocks &

# Remove top padding so fullscreen apps cover the whole screen, including over Polybar
#bspc config top_padding 0

#default firefox
xdg-settings set default-web-browser firefox.desktop &
 
# Terminal to use
TERMINAL=kitty

# Window gaps and borders
bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config normal_border_color  "#661111"
bspc config focused_border_color "#cc0000"

# ⛔ Don't automatically focus windows when the mouse hovers
bspc config focus_follows_pointer true

# ✅ Do focus a window when you click on it (with mouse/trackpad)
bspc config click_to_focus false

#pointer follows
bspc config pointer_follows_focus false

# Set default desktop layout
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Reverse touchpad scrolling
xinput set-prop "SYNA7DB5:00 06CB:CD41 Touchpad" "libinput Natural Scrolling Enabled" 1

#when full sceen hide polybar 
~/.config/bspwm/fullscreen-watcher.sh &

