-- return {
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "custom", -- use your scheme
--     },
--   },
-- }
-- return {
--   -- add gruvbox
--   { "ellisonleao/gruvbox.nvim" },
--
--   -- Configure LazyVim to load gruvbox
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "gruvbox",
--     },
--   },
-- }
-- another gruvbox colorscheme (personal liking)
-- lua/plugins/gruvbox.lua
return {
  "https://gitlab.com/motaz-shokry/gruvbox.nvim",
  name = "gruvbox",
  priority = 1000,
  config = function()
    vim.cmd("colorscheme gruvbox-hard")
    -- vim.cmd("hi Normal guibg=NONE")
  end,
}
-- idk
-- return {
--   "bluz71/vim-moonfly-colors",
--   name = "moonfly",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.cmd("colorscheme moonfly")
--   end,
-- }
-- monochrome theme colorscheme
-- return {
--   "kdheepak/monochrome.nvim",
--   name = "monochrome",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.cmd("colorscheme monochrome")
--   end,
-- }
-- Lua with Lazy.nvim:
-- return {
--   "Mofiqul/adwaita.nvim",
--   lazy = false,
--   priority = 1000,
--
--   -- configure and set on startup
--   config = function()
--     vim.g.adwaita_darker = true -- for darker version
--     vim.g.adwaita_disable_cursorline = true -- to disable cursorline
--     vim.g.adwaita_transparent = true -- makes the background transparent
--     vim.cmd("colorscheme adwaita")
--   end,
-- }
---- pywal script
-- return {
--   "AlphaTechnolog/pywal.nvim",
--   name = "pywal",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.cmd("colorscheme pywal")
--   end,
-- }
-- lua/plugins/rose-pine.lua
-- return {
--   "rose-pine/neovim",
--   name = "rose-pine",
--   config = function()
--     vim.cmd("colorscheme rose-pine")
--   end,
-- }
