return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	branch = "main",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").install({
			"bash",
			"c",
			"cpp",
			"diff",
			"html",
			"javascript",
			"java",
			"jsdoc",
			"json",
			"jsonc",
			"kotlin",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"query",
			"rust",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zig",
		})
	end,
}
-- return {
-- 	{
-- 		"nvim-treesitter/nvim-treesitter",
-- 		lazy = false,
-- 		-- branch = "main",
-- 		build = ":TSUpdate",
-- 		opts = {
-- 			auto_install = true,
-- 			sync_install = true,
-- 			highlight = { enable = true },
-- 			indent = { enable = true },
-- 			ensure_installed = {
-- 				"bash",
-- 				"c",
-- 				"cpp",
-- 				"diff",
-- 				"html",
-- 				"javascript",
-- 				"java",
-- 				"jsdoc",
-- 				"json",
-- 				"jsonc",
-- 				"lua",
-- 				"luadoc",
-- 				"luap",
-- 				"markdown",
-- 				"markdown_inline",
-- 				"printf",
-- 				"python",
-- 				"query",
-- 				"regex",
-- 				"toml",
-- 				"tsx",
-- 				"typescript",
-- 				"vim",
-- 				"vimdoc",
-- 				"xml",
-- 				"yaml",
-- 			},
-- 		},
-- 	},
-- }
